spring.application.name=cohabit-backend

spring.datasource.url=jdbc:mysql://localhost:3306/cohabit
spring.datasource.username=root
spring.datasource.password=KSVF5636

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true